---
name: Build Monero package
permissions: {}
on:
  push:
    paths:
      - 'monero/monero.spec'

jobs:
  call-webhook:
    uses: zpc0/fedora-monero/.github/workflows/webhook.yml@master
    with:
      package-name: monero
    secrets:
      uuid: ${{ secrets.UUID }}

