---
name: Build XMRig package
permissions: {}
on:
  push:
    paths:
      - 'xmrig/xmrig.spec'

jobs:
  call-webhook:
    uses: zpc0/fedora-monero/.github/workflows/webhook.yml@master
    with:
      package-name: xmrig
    secrets:
      uuid: ${{ secrets.UUID }}

